---
#
# Web playbook for the front web server
#

- name: "----------------------- Start Web playbook ------------------------"
  hosts: front_server
  become: true
  gather_facts: no
  pre_tasks:
    - name: "Install python2"
      raw: sudo apt-get -y install python python-simplejson
  become_user: root
  user: ubuntu
  roles:
    - common
    - apache
    - php
    - mysql
    - redis