---
- name: Deploy application
  hosts: all
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../../../shared/www/"
    ansistrano_deploy_to: "/var/www/html"
    ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/infrastructure.yml"
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/after_symlink.yml"
    ansistrano_current_dir: "current"
    ansistrano_current_via: "symlink"
    ansistrano_keep_releases: 3
    ansistrano_allow_anonymous_stats: false
  roles:
    - carlosbuenosvinos.ansistrano-deploy